In [50]:
import pandas as pd

data = pd.read_csv("Train_churn.csv")

In [51]:
data = data.set_index(['ID'])
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
data['Gender'] = label_encoder.fit_transform(data['Gender'])

In [52]:
data

,Age,Gender,Income,Balance,Vintage,Transaction_Status,Product_Holdings,Credit_Card,Credit_Category,Is_Churn
ID,,,,,,,,,,
84e2fcc9,36,0,5L - 10L,563266.44,4,0,1,0,Average,1
57fea15e,53,0,Less than 5L,875572.11,2,1,1,1,Poor,0
8df34ef3,35,0,More than 15L,701607.06,2,1,2,0,Poor,0
c5c0788b,43,0,More than 15L,1393922.16,0,1,2,1,Poor,1
951d69c4,39,0,More than 15L,893146.23,1,1,1,1,Good,1
...,...,...,...,...,...,...,...,...,...,...
a8216afd,61,1,5L - 10L,1354526.19,4,1,2,1,Poor,1
153a306b,42,0,5L - 10L,596286.54,3,1,2,1,Average,0
d4075a95,29,1,Less than 5L,979298.19,2,0,2,0,Poor,0
5855b142,66,0,10L - 15L,395233.65,3,0,2,1,Poor,1
57b39511,37,1,More than 15L,826947.27,1,1,2,0,Good,0

In [53]:
a = []
for cc in data.Credit_Category:
    if(cc[0]=='P'):
        a.append(-1)
    elif(cc[0]=='A'):
        a.append(0)
    else:
        a.append(1)

In [54]:
data.Credit_Category = a

In [55]:
a = []
for cc in data.Income:
    if(cc[0]=='L'):
        a.append(-1)
    elif(cc[0]=='5'):
        a.append(0)
    else:
        a.append(1)

In [56]:
data.Income = a

In [57]:
a = [] 
for i in data.Product_Holdings:
    if(i[0]=='3'):
        a.append(3)
    else:
        a.append(int(i))
data.Product_Holdings=a

In [58]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data.drop(['Is_Churn'],axis=1), data.Is_Churn , test_size=0.25, random_state=0)

In [59]:
from sklearn.preprocessing import StandardScaler

ss_train = StandardScaler()
X_train = ss_train.fit_transform(X_train)

ss_test = StandardScaler()
X_test = ss_test.fit_transform(X_test)

In [60]:
X_train

array([[-0.8488758 , -1.0940367 ,  0.92284041, ..., -0.98093842,
         0.70700044, -0.95484257],
       [-1.05653516,  0.91404612,  0.92284041, ..., -0.98093842,
         0.70700044,  0.29727415],
       [ 1.0200584 , -1.0940367 , -1.52905364, ..., -0.98093842,
         0.70700044, -0.95484257],
       ...,
       [ 0.0855913 ,  0.91404612, -0.30310661, ..., -0.98093842,
         0.70700044, -0.95484257],
       [ 2.16218485, -1.0940367 ,  0.92284041, ...,  0.7680569 ,
         0.70700044, -0.95484257],
       [ 1.0200584 ,  0.91404612, -0.30310661, ...,  2.51705221,
         0.70700044,  1.54939088]])

In [61]:
models = {}

# Logistic Regression
from sklearn.linear_model import LogisticRegression
models['Logistic Regression'] = LogisticRegression()

# Support Vector Machines
from sklearn.svm import LinearSVC
models['Support Vector Machines'] = LinearSVC()

# Decision Trees
from sklearn.tree import DecisionTreeClassifier
models['Decision Trees'] = DecisionTreeClassifier()

# Random Forest
from sklearn.ensemble import RandomForestClassifier
models['Random Forest'] = RandomForestClassifier()

# Naive Bayes
from sklearn.naive_bayes import GaussianNB
models['Naive Bayes'] = GaussianNB()

# K-Nearest Neighbors
from sklearn.neighbors import KNeighborsClassifier
models['K-Nearest Neighbor'] = KNeighborsClassifier()

In [62]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

accuracy, precision, recall = {}, {}, {}

for key in models.keys():
    
    # Fit the classifier
    models[key].fit(X_train, y_train)
    
    # Make predictions
    predictions = models[key].predict(X_test)
    
    # Calculate metrics
    accuracy[key] = accuracy_score(predictions, y_test)
    precision[key] = precision_score(predictions, y_test)
    recall[key] = recall_score(predictions, y_test)

In [63]:
df_model = pd.DataFrame(index=models.keys(), columns=['Accuracy', 'Precision', 'Recall'])
df_model['Accuracy'] = accuracy.values()
df_model['Precision'] = precision.values()
df_model['Recall'] = recall.values()

df_model

                         Accuracy  Precision    Recall
Logistic Regression      0.770896   0.049223  0.575758
Support Vector Machines  0.772099   0.023316  0.818182
Decision Trees           0.665063   0.272021  0.275591
Random Forest            0.755262   0.106218  0.398058
Naive Bayes              0.762477   0.069948  0.428571
K-Nearest Neighbor       0.733614   0.132124  0.320755

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential() 
model.add(Dense(128, activation='relu', input_dim=X_train[0].size))
model.add(Dense(1, activation='sigmoid')) 
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) 
model.summary()

In [ ]:
import keras.models

In [ ]:
import keras